#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{if .Root}}(Admin){{end}} {{ .PWD }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  # [[blocks.segments]]
  #   type = 'session'
  #   style = 'plain'
  #   foreground = '#BF616A'
  #   template = '{{ .UserName }} '

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = 'blue'
    background = 'transparent'
    template = '➜ '

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = '#81A1C1'
    background = 'transparent'
    template = '{{ path .Path .Location }} '

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'p:grey'
    background = 'transparent'
    template = '{{ .HEAD }}{{if or (.Working.Changed) (.Staging.Changed)}}*{{end}}{{if gt .Behind 0}}⇣{{end}}{{if gt .Ahead 0}}⇡{{end}} '

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = 'green'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}"
    ]
    background = 'transparent'
    template = '{{if eq .UserName "root" }}#{{else}}🞂{{end}}'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}"
  ]
  foreground = 'green'
  background= 'transparent'
  template = '~ '

[secondary_prompt]
  foreground = '#3c3c3c'
  background = 'transparent'
  template = '~> '

[pallete]
grey = '#6c6c6c'
